import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#3b3b3b',
  },
  back: {
    width: 25,
    height: 25,
  },
  backButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 20,
    position: 'absolute',
    borderRadius: 50,
  },
  pickerArea: {
    width: '50%',
    elevation: 5,
    backgroundColor: '#fff',
    borderRadius: 10,
    margin: 20,
    justifyContent: 'center',
  },
  main: {
    alignItems: 'center',
    backgroundColor: '#3b3b3b',
    flex: 1,
  },
  foto: {
    margin: 25,
    marginBottom: 0,
    width: 100,
    height: 100,
    borderRadius: 100,
    borderColor: '#f0f0f0',
    borderWidth: 5,
  },
  nama: {
    fontSize: 24,
    color: '#fff',
    margin: 20,
    fontWeight: 'bold',
  },
  button: {
    backgroundColor: '#FFCC57',
    width: 200,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    // position: 'absolute',
    marginTop: 50,
    marginLeft: 100,
  },
  buttonText: {
    color: '#3b3b3b',
    fontWeight: 'bold',
    fontSize: 16,
  },
  image: {
    borderWidth: 3,
    borderColor: '#fff',
    width: 125,
    height: 125,
    borderRadius: 15,
  },
  jenisSampah: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 150,
  },
  Berat: {
    width: '90%',
    elevation: 5,
    backgroundColor: '#fff',
    borderRadius: 10,
    margin: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  beratInput: {
    width: '80%',
    padding: 10,
    fontSize: 16,
  },
  pickerSampahArea: {
    width: '50%',
    height: '40%',
    elevation: 5,
    backgroundColor: '#fff',
    borderRadius: 10,
    margin: 20,
    justifyContent: 'center',
  },
  kilo: {
    fontSize: 16,
    fontWeight: 'bold',
  },
});
